# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm install -g yarn@^1.19.0
    - run: yarn install --frozen-lockfile
    - run: yarn gulp lint release
      env:
        NODE_OPTIONS: --max_old_space_size=4096
